# Install command-line tools using Homebrew
#
#   brew bundle --file=~/.dotfiles/Brewfile

tap 'homebrew/cask'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'homebrew/services'

brew 'ansible'
brew 'bat'
# brew 'cowsay'
brew 'docker-compose'
brew 'exa'
brew 'fd'
# brew 'fzf'
brew 'git'
brew 'go'
brew 'htop'
brew 'httpie'
brew 'jq'
brew 'node'
brew 'postgresql'
brew 'ripgrep'
# brew 'rsync'
# brew 'tree'
brew 'wget'
brew 'yarn'
# brew 'zsh'
brew 'pure'
# brew 'spaceship'
# brew 'boot2docker'
# brew 'docker-machine'
# brew 'figlet'
# brew 'pow'
# brew 'pyenv'
# brew 'rbenv'
# brew 'rclone'
# brew 'lame'
# brew 'micro'
# brew 'neovim'
# brew 'nnn'

# Desktop apps
cask 'firefox'
cask 'zoomus'
cask '1password'
cask 'cleanshot'
cask 'rectangle'
cask 'tunnelbear'
cask 'dropbox'
cask 'telegram-desktop'
# cask 'cleanmymac'
cask 'hammerspoon'
cask 'slack'
# cask 'spotify'
cask 'sublime-text'
cask 'sublime-merge'
cask 'iterm2'
# cask 'keybase'
# cask 'ableton-live-suite'
# cask 'ilya-birman-typography-layout'
# cask 'google-chrome'
# cask 'qlcolorcode'
# cask 'quicklook-json'
cask 'qlmarkdown'
cask 'docker'
cask 'bartender'
cask 'xbar'

# Fonts
cask 'font-jetbrains-mono'
# cask 'font-anonymous-pro'
# cask 'font-droid-sans'
# cask 'font-droid-sans-mono'
# cask 'font-inconsolata'
# cask 'font-pt-mono'
# cask 'font-pt-sans'
# cask 'font-pt-serif'
# cask 'font-roboto'
# cask 'font-roboto-mono'
